name: Commit to Master
on:
  push:
    branches:
      - master
jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - run: yarn
      - run: yarn prepublishOnly
      - uses: 'scaffoldly/github-action-bump-version-npm@master'
        with:
          tag-prefix: ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
