name: Push to Main
on:
  push:
    branches:
      - main
jobs:
  prerelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - run: yarn
      - run: yarn prepublishOnly
      - uses: scaffoldly/bump-version-action@1.0.83
        with:
          action: prerelease
          version-file: package.json
          repo-token: ${{ secrets.GITHUB_TOKEN }}
